### PR TITLE
[WIP] Tap overhaul

### PR DESCRIPTION
**Pull request by smoh**
@jcsegovia @bsipocz @keflavich

This pull request is to work on this [upstream pull request](https://github.com/astropy/astroquery/pull/1266).
Here are some changes I made mostly related to comments I made already and confined to `Tap` class.

I happen to know that there are other TAP clients (not TAP+): one written already by @mfouesneau [here](https://github.com/mfouesneau/tap) and one available at [pyvo](https://github.com/pyvirtobs/pyvo/blob/master/pyvo/dal/tap.py). Since ESAC Space Data Centre extended TAP to TAP+ with many useful additional capabilities which is applicable to Gaia and it seems like this module in astroquery will be maintained and updated officially, I think it makes sense to have astroquery's own Tap and TapPlus. But I am mentioning the others here as references as they both use requests library and tend to require much less code.

I know this can be quite an overhaul of the code already written, but maybe now is the best time to bring this up.

I allowed edits from maintainers but I guess this doesn't include upstream maintainers? The changes I made so far are small so if it's easier to have this happen somewhere else, feel free take these there. Otherwise I will keep this open and push changes I make.

### CODE REVIEW

**Comment by smoh** [comment]
After working on this for the last few days, I'd actually like to ask the authors to wait and _not_ to push to this pull request. These will be substantial and API breaking changes and I think it will be disruptive to have multiple people working on it.

I made an effort to make the commit messages as clear as possible. If there's any issue with the changes, let me know.

**Comment by smoh** [comment]
- I removed `list_async_jobs` method. Even before #1266, this method returns some 66000 job list in 8 minutes. I am guessing it scrapes the entire async jobs on the server (to some server-set limit). It's hard to imagine a general usage of this method.

```sh
# this is on master
❯ time python -c "from astroquery.gaia import Gaia; print(len(Gaia.list_async_jobs()))"
Created TAP+ (v1.0.1) - Connection:
        Host: gea.esac.esa.int
        Use HTTPS: False
        Port: 80
        SSL Port: 443
66433
python -c   7.84s user 2.18s system 6% cpu 2:37.86 total
```

**Comment by smoh** [comment]
FYI: there's actually a whole separate python package [pytables](http://pytables.org) so it can be confusing to refer astropy tables as pytables.

**Comment by smoh** [comment]
In the spirit of keeping everyone posted:

I have now made quite a few of methods tidy with requests; a request session is attached to Tap instance and many of the low-level hardcoded parts like
- building url parameters `url?param1=value1&param2=value2`
- managing session cache
- passing form values

are handled by requests. These changes can be reviewed in tap/core.py diff.

The general structure of a method is
```python
def query(self, *args, **kwargs):
    url = <construct correct url string>
    <prepare params, args, files>
    response =  self.session.post/get(url, params=<params>, data=<args>, files=<files>
    <parse response>
```

As I move on to adding group/share capabilities and datalinks and parsing response, it is clear to me that TAP+ is really specifically developed for Gaia and not generally applicable to any other service (at least not yet). The previous documentation about using TAP+ with other service is misleading because pretty much all of TAP+ specific capabilities will not work with other TAP services. Thus, I'd like to suggest that we move all of astroquery/utils/tap to gaia and perhaps just make TapPlus -> GaiaTapPlus.

Other notable changes and style notes for the future:
- If a parameter is required for a function/method to run, make it an argument not `keyword=None` and check `if keyword is None`.
- Avoid unnecessary nesting like
```python
def do_something(*args, **kwargs):
    ...
    return actually_do_something(*args, **kwargs)
```
- Change method names `launch_job` and `launch_job_async` to `query` and `query_async`.
- I think `load_table(s)` can also be better named.
- I plan to use [xml.etree](https://docs.python.org/3/library/xml.etree.elementtree.html) for xml parsing instead of SAX parser originally used.

Feedback welcome.

**Comment by keflavich** [comment]
@smoh All of the changes you suggest sound good to me. 

On the XML parsing: is this really raw XML or is it votable XML?  If the latter, we should use astropy's votable reader.

**Comment by smoh** [comment]
> On the XML parsing: is this really raw XML or is it votable XML? If the latter, we should use astropy's votable reader.

I think we require both as it is not just votables that are returned in xml. Specifically, UWS Job patterns (http://www.ivoa.net/documents/UWS/). I got this parsing working quite easily with xml.etree (code not checked in yet) but for votable xml, will do (perhaps it's already done that way; haven't encountered yet).

 I think I also found that there was a generic "list of astropy tables" class written somewhere in astroquery and thought it maybe more useful to use that instead of current behavior that returns list of TapTableMeta.

```python
In [2]: Gaia.load_tables()
Retrieving tables...
Parsing tables...
Done.
Out[2]:
[<astroquery.utils.tap.model.taptable.TapTableMeta at 0x817b5c5f8>,
 <astroquery.utils.tap.model.taptable.TapTableMeta at 0x817b21c88>,
 <astroquery.utils.tap.model.taptable.TapTableMeta at 0x817b21d68>,
 <astroquery.utils.tap.model.taptable.TapTableMeta at 0x817c1a160>,
 <astroquery.utils.tap.model.taptable.TapTableMeta at 0x817c14160>,
....]
```

**Comment by smoh** [comment]
One more thing: I found that it is essential to include `TASKID` parameter when uploading user table otherwise I get 500 Internal Server Error. This is not documented in the official Gaia page and almost certainly seems like an upstream bug on the server side...

**Comment by smoh** [comment]
Ah... This was really NOT ready to be merged.

**Comment by jcsegovia** [comment]
@smoh apologies! What do you prefer to do? I can revert your latest changes, is that what you want/need...?

**Comment by smoh** [comment]
Yes, if you can? I think you may have to force push to master of this repo. The work is not finished and I know it will break stuff as of now.

**Pull request merged**
